# Generated by Django 4.2.2 on 2023-06-16 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userrole_user_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Perfiles de usuario'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name_plural': 'Roles de usuario'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_role',
        ),
    ]
